// <auto-generated />
using System;
using CarPool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPool.Data.Migrations
{
    [DbContext(typeof(CarPoolDBContext))]
    [Migration("20211128135955_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(8463),
                            IsDeleted = false,
                            Latitude = 42.6860436m,
                            Longitude = 23.320311m,
                            StreetName = "Vasil Levski 14"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(552),
                            IsDeleted = false,
                            Latitude = 42.1382775m,
                            Longitude = 24.7604295m,
                            StreetName = "blv. Iztochen 23"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(591),
                            IsDeleted = false,
                            Latitude = 41.022079m,
                            Longitude = 28.9483964m,
                            StreetName = "blv. Halic 12"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(595),
                            IsDeleted = false,
                            Latitude = 37.9916167m,
                            Longitude = 23.7363294m,
                            StreetName = "blv. Zeus 12"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(597),
                            IsDeleted = false,
                            Latitude = 44.432558m,
                            Longitude = 26.111871m,
                            StreetName = "blv. Romunska Morava 1"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(601),
                            IsDeleted = false,
                            Latitude = 44.432558m,
                            Longitude = 26.111871m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(603),
                            IsDeleted = false,
                            Latitude = 44.432558m,
                            Longitude = 26.111871m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(606),
                            IsDeleted = false,
                            Latitude = 44.432558m,
                            Longitude = 26.111871m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(608),
                            IsDeleted = false,
                            Latitude = 44.432558m,
                            Longitude = 26.111871m
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(1222),
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(1438),
                            IsDeleted = false,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(1446),
                            IsDeleted = false,
                            Name = "Banned"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(1447),
                            IsDeleted = false,
                            Name = "NotConfirmed"
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");

                    b.HasCheckConstraint("Password_contains_space", "Password NOT LIKE '% %'");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            AddressId = 1,
                            ApplicationRoleId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 768, DateTimeKind.Utc).AddTicks(3313),
                            Email = "mishkov@misho.com",
                            EmailConfirmed = true,
                            FirstName = "Misho",
                            LastName = "Mishkov",
                            Password = "$2a$11$LWFif1EfXutqX3.zj5v8N.R.gTOfwbZ6qf8YieUibZXc//Yw9NK32",
                            PhoneNumber = "+35920768005",
                            Username = "misha_m"
                        },
                        new
                        {
                            Id = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            AddressId = 2,
                            ApplicationRoleId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 889, DateTimeKind.Utc).AddTicks(2992),
                            Email = "petio@mvc.net",
                            EmailConfirmed = true,
                            FirstName = "Peter",
                            LastName = "Petrov",
                            Password = "$2a$11$nJ0nbqV8ZFuk33Q2yN7cZuR0ALnfOlVP400oO1eQJ2fQi8RA9uGCK",
                            PhoneNumber = "+35924492877",
                            Username = "petio_p"
                        },
                        new
                        {
                            Id = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            AddressId = 3,
                            ApplicationRoleId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 5, DateTimeKind.Utc).AddTicks(4185),
                            Email = "koksal@asd.tr",
                            EmailConfirmed = true,
                            FirstName = "Koksal",
                            LastName = "Baba",
                            Password = "$2a$11$R8xpQnAsBKgpVD1.VgIWoeLyIvMHdxeRs9ctfwhXbl0BddMjIXHku",
                            PhoneNumber = "+35922649764",
                            Username = "koksal"
                        },
                        new
                        {
                            Id = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            AddressId = 1,
                            ApplicationRoleId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 120, DateTimeKind.Utc).AddTicks(7060),
                            Email = "indebt@greece.gov",
                            EmailConfirmed = true,
                            FirstName = "Nikolaos",
                            LastName = "Tsitsibaris",
                            Password = "$2a$11$VpaZ8LYDFI4dz0oA1hGlPusaUMH9ILj/SwyTSZ7I3dsJmXw3kkYfy",
                            PhoneNumber = "+35924775508",
                            Username = "cicibar"
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BlockedDue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BlockedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Ban");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            BlockedDue = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            BlockedOn = new DateTime(2021, 11, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 236, DateTimeKind.Utc).AddTicks(9463)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            BlockedOn = new DateTime(2021, 11, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 238, DateTimeKind.Utc).AddTicks(8038)
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(6047),
                            IsDeleted = false,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7101),
                            IsDeleted = false,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7128),
                            IsDeleted = false,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7130),
                            IsDeleted = false,
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7131),
                            IsDeleted = false,
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7135),
                            IsDeleted = false,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7136),
                            IsDeleted = false,
                            Name = "Patras"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7137),
                            IsDeleted = false,
                            Name = "Yash"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7138),
                            IsDeleted = false,
                            Name = "Odrin"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7140),
                            IsDeleted = false,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7141),
                            IsDeleted = false,
                            Name = "Bucharest"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 767, DateTimeKind.Utc).AddTicks(7142),
                            IsDeleted = false,
                            Name = "Craiova"
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 766, DateTimeKind.Utc).AddTicks(4461),
                            IsDeleted = false,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 766, DateTimeKind.Utc).AddTicks(5487),
                            IsDeleted = false,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 766, DateTimeKind.Utc).AddTicks(5507),
                            IsDeleted = false,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 54, 766, DateTimeKind.Utc).AddTicks(5509),
                            IsDeleted = false,
                            Name = "Romania"
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.GoogleAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GoogleAccount");
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.ProfilePicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("ProfilePictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(4369),
                            ImageLink = "https://ik.imagekit.io/hb0rsbgap4f2/profilepicture_qVGMALiir.png?updatedAt=1637784974343",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(4826),
                            ImageLink = "https://ik.imagekit.io/hb0rsbgap4f2/profilepicture_qVGMALiir.png?updatedAt=1637784974343",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(4852),
                            ImageLink = "https://ik.imagekit.io/hb0rsbgap4f2/profilepicture_qVGMALiir.png?updatedAt=1637784974343",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(4853),
                            ImageLink = "https://ik.imagekit.io/hb0rsbgap4f2/profilepicture_qVGMALiir.png?updatedAt=1637784974343",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedByUserId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(5515),
                            Feedback = "Nice car",
                            TripId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 2,
                            AddedByUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            ApplicationUserId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(6790),
                            Feedback = "Bad person",
                            TripId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            AddedByUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(6819),
                            Feedback = "(No feedback)",
                            TripId = 5,
                            Value = 5
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationAddressId")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("FreeSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassengersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StartAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAddressId");

                    b.HasIndex("DriverId");

                    b.HasIndex("StartAddressId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalComment = "(No comment)",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 238, DateTimeKind.Utc).AddTicks(9936),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(1050),
                            DestinationAddressId = 2,
                            Distance = 340,
                            DriverId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            DurationInMinutes = 90,
                            FreeSeats = 2,
                            PassengersCount = 2,
                            Price = 0m,
                            StartAddressId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdditionalComment = "NO SMOKING",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2092),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2121),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 2,
                            Price = 0m,
                            StartAddressId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdditionalComment = "NO SMOKING",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2157),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2159),
                            DestinationAddressId = 2,
                            Distance = 210,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 110,
                            FreeSeats = 2,
                            PassengersCount = 2,
                            Price = 0m,
                            StartAddressId = 4
                        },
                        new
                        {
                            Id = 4,
                            AdditionalComment = "Long comment here",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2162),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2163),
                            DestinationAddressId = 1,
                            Distance = 240,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 4
                        },
                        new
                        {
                            Id = 5,
                            AdditionalComment = "Additional comments below",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2166),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2167),
                            DestinationAddressId = 4,
                            Distance = 240,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 1
                        },
                        new
                        {
                            Id = 6,
                            AdditionalComment = "follow me on twitter",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2171),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2173),
                            DestinationAddressId = 4,
                            Distance = 240,
                            DriverId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 2
                        },
                        new
                        {
                            Id = 7,
                            AdditionalComment = "NO EATING",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2175),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2176),
                            DestinationAddressId = 2,
                            Distance = 240,
                            DriverId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 4
                        },
                        new
                        {
                            Id = 8,
                            AdditionalComment = "CHEAP AND FAST",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2179),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2180),
                            DestinationAddressId = 2,
                            Distance = 240,
                            DriverId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 1
                        },
                        new
                        {
                            Id = 9,
                            AdditionalComment = "FAST FAST FAST",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2182),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2183),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 2
                        },
                        new
                        {
                            Id = 10,
                            AdditionalComment = "No pets",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2187),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2188),
                            DestinationAddressId = 1,
                            Distance = 240,
                            DriverId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 0m,
                            StartAddressId = 3
                        },
                        new
                        {
                            Id = 11,
                            AdditionalComment = "NO SMOKING NO FOOD",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2191),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2192),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 19.11m,
                            StartAddressId = 1
                        },
                        new
                        {
                            Id = 12,
                            AdditionalComment = "NO STOPS",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2468),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2474),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 15.55m,
                            StartAddressId = 4
                        },
                        new
                        {
                            Id = 13,
                            AdditionalComment = "Good looking and friendly",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2494),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2495),
                            DestinationAddressId = 4,
                            Distance = 240,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 10.13m,
                            StartAddressId = 3
                        },
                        new
                        {
                            Id = 14,
                            AdditionalComment = "Fast car",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2498),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2499),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 10.11m,
                            StartAddressId = 1
                        },
                        new
                        {
                            Id = 15,
                            AdditionalComment = "High price",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2502),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2503),
                            DestinationAddressId = 2,
                            Distance = 240,
                            DriverId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 15.21m,
                            StartAddressId = 3
                        },
                        new
                        {
                            Id = 16,
                            AdditionalComment = "Im not alone",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2506),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2507),
                            DestinationAddressId = 1,
                            Distance = 240,
                            DriverId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 2,
                            Price = 21.21m,
                            StartAddressId = 2
                        },
                        new
                        {
                            Id = 17,
                            AdditionalComment = "No kids",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 239, DateTimeKind.Utc).AddTicks(2509),
                            DepartureTime = new DateTime(2021, 11, 28, 15, 59, 55, 239, DateTimeKind.Local).AddTicks(2510),
                            DestinationAddressId = 3,
                            Distance = 240,
                            DriverId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            DurationInMinutes = 120,
                            FreeSeats = 2,
                            PassengersCount = 1,
                            Price = 12.23m,
                            StartAddressId = 1
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.TripPassenger", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationUserId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("TripPassengers");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            TripId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            TripId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            TripId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            TripId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            TripId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            TripId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.UserVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("FuelConsumptionPerHundredKilometers")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("UserVehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = new Guid("e7d1610a-07d2-4292-a3e8-03736c29e5de"),
                            Color = "Red",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 236, DateTimeKind.Utc).AddTicks(6935),
                            FuelConsumptionPerHundredKilometers = 12.0,
                            IsDeleted = false,
                            Model = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = new Guid("669f1b05-ab0b-42a7-9aec-82106113dd79"),
                            Color = "Blue",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 236, DateTimeKind.Utc).AddTicks(8121),
                            FuelConsumptionPerHundredKilometers = 8.0,
                            IsDeleted = false,
                            Model = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = new Guid("cfddfdde-ad77-420f-9c5e-f57192666cc0"),
                            Color = "Black",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 236, DateTimeKind.Utc).AddTicks(8168),
                            FuelConsumptionPerHundredKilometers = 10.0,
                            IsDeleted = false,
                            Model = "Mercedes S Class"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = new Guid("5bbbd751-6267-464c-a649-5f92e7d23d0e"),
                            Color = "Silver",
                            CreatedOn = new DateTime(2021, 11, 28, 13, 59, 55, 236, DateTimeKind.Utc).AddTicks(8188),
                            FuelConsumptionPerHundredKilometers = 15.0,
                            IsDeleted = false,
                            Model = "BMW M5"
                        });
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Address", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.ApplicationUser", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.Address", "Address")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ApplicationRoleId");
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Ban", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Ban")
                        .HasForeignKey("CarPool.Data.Models.DatabaseModels.Ban", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.City", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.ProfilePicture", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "ApplicationUser")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("CarPool.Data.Models.DatabaseModels.ProfilePicture", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Rating", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "ApplicationUser")
                        .WithMany("Ratings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.Trip", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.Address", "DestinationAddress")
                        .WithMany("TripsDestinationAddress")
                        .HasForeignKey("DestinationAddressId")
                        .HasConstraintName("FK_Trips_DestinationAddresses")
                        .IsRequired();

                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("FK_Trips_ApplicationUsers")
                        .IsRequired();

                    b.HasOne("CarPool.Data.Models.DatabaseModels.Address", "StartAddress")
                        .WithMany("TripsStartAddress")
                        .HasForeignKey("StartAddressId")
                        .HasConstraintName("FK_Trips_StartAddresses")
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.TripPassenger", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "ApplicationUser")
                        .WithMany("TripsAsPassenger")
                        .HasForeignKey("ApplicationUserId")
                        .HasConstraintName("FK_TripPassengerRelation_ApplicationUsers")
                        .IsRequired();

                    b.HasOne("CarPool.Data.Models.DatabaseModels.Trip", "Trip")
                        .WithMany("Passengers")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_TripPassengerRelation_Trips")
                        .IsRequired();
                });

            modelBuilder.Entity("CarPool.Data.Models.DatabaseModels.UserVehicle", b =>
                {
                    b.HasOne("CarPool.Data.Models.DatabaseModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Vehicle")
                        .HasForeignKey("CarPool.Data.Models.DatabaseModels.UserVehicle", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
